FROM ubuntu:latest AS nuclei-snippets-scanner
WORKDIR /nuclei-snippets

# Install dependencies and basic tools in a single layer
RUN apt-get update && apt-get install -y --no-install-recommends \
    bash \
    ca-certificates \
    curl \
    dnsutils \
    git \
    grepcidr \
    iputils-ping \
    jq \
    libasound2t64 \
    libatk-bridge2.0-0 \
    libatk1.0-0 \
    libgbm1 \
    libgtk-3-0 \
    libnet-ssleay-perl \
    libnss3 \
    libpangocairo-1.0-0 \
    # libpcap-dev required by naabu
    libpcap-dev \
    libx11-xcb1 \
    libxcb-dri3-0 \
    libxcomposite1 \
    libxdamage1 \
    libxfixes3 \
    libxrandr2 \
    net-tools \
    netcat-openbsd \
    nmap \
    perl \
    python3 \
    python3-pip \
    unzip \
    vim \
    wget \
    zip \
    && update-ca-certificates \
    && rm -rf /var/lib/apt/lists/*

# Golang
ENV HOME=/root
ENV GOROOT=/usr/local/go
ENV GOPATH=$HOME/go
ENV PDTM_PATH=$HOME/.pdtm/go/bin
ENV PATH=$PATH:$GOPATH/bin:$GOROOT/bin:$PDTM_PATH

RUN wget -q https://go.dev/dl/go1.23.6.linux-amd64.tar.gz \
    && tar -C /usr/local -xzf go1.23.6.linux-amd64.tar.gz \
    && rm go1.23.6.linux-amd64.tar.gz

# Project Discovery + Anew
RUN go install -v github.com/projectdiscovery/pdtm/cmd/pdtm@latest \
    && pdtm -ia \
    && nuclei -update-templates \
    && go install -v github.com/tomnomnom/anew@latest

# Cache & Config Directory
RUN mkdir -p /root/.cache/nuclei
