version: "3"

services:
  scanner:
    build:
      context: .
      dockerfile: Dockerfile.scanner
    container_name: nuclei-snippets-scanner
    working_dir: ${BASE_DIR}
    restart: always
    image: nuclei-snippets-scanner
    stdin_open: true
    tty: true
    volumes:
      - ./templates:${TEMPLATES_DIR}
      - ./shared:${SHARED_DIR}
      - ./container/scripts:${SCRIPTS_DIR}
    env_file:
      - .env
    ports:
      - "9092:9092"
    networks:
      scanner_network:
        ipv4_address: "172.25.0.2"
    extra_hosts:
      - "target.local:172.25.0.3"

  apache:
    image: "php:7.2-apache"
    stdin_open: true
    tty: true
    container_name: nuclei-snippets-apache
    restart: always
    ports:
      - "1337:80"
    volumes:
      - ./container/php:/var/www/html
      - ./shared:/shared
    networks:
      scanner_network:
        ipv4_address: "172.25.0.3"

  smtp4dev:
    container_name: nuclei-snippets-smtp
    image: rnwood/smtp4dev
    expose:
      - 2525
      - 1080
    ports:
      - 2525:25
      - 1080:80
    networks:
      scanner_network:
        ipv4_address: "172.25.0.4"

  endlessh:
    image: lscr.io/linuxserver/endlessh:latest
    container_name: nuclei-snippets-ssh
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    ports:
      - 22:2222
    restart: unless-stopped
    networks:
      scanner_network:
        ipv4_address: "172.25.0.5"

networks:
  scanner_network:
    ipam:
      driver: default
      config:
        - subnet: "172.25.0.0/16"
          gateway: "172.25.0.1"
